---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-service
  labels:
    app: stremio
    role: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stremio
      role: server
  template:
    metadata:
      labels:
        app: stremio
        role: server
    spec:
      volumes:
      - name: openvpn-configuration
        secret:
          secretName: openvpn-configuration
          items:
          - key: custom.ovpn
            path: custom.conf
      containers:
      - name: gluetun
        image: ghcr.io/qdm12/gluetun
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: TZ
          value: Europe/Paris
        - name: VPN_SERVICE_PROVIDER
          value: custom
        - name: OPENVPN_CUSTOM_CONFIG
          value: /gluetun/custom.conf
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-credentials
              key: username
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openvpn-credentials
              key: password
        volumeMounts:
        - name: openvpn-configuration
          mountPath: /gluetun/custom.conf
          subPath: custom.conf
          readOnly: true
      - name: stremio-service
        image: ghcr.io/rpersee/stremio/server:4.20.3
        ports:
        - containerPort: 11470
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              awk 'BEGIN {rc=1} $1 == "tun0" && $2 == "00000000" {rc=0} END {exit rc}' /proc/net/route
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-web
  labels:
    app: stremio
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stremio
      role: client
  template:
    metadata:
      labels:
        app: stremio
        role: client
    spec:
      containers:
      - name: stremio-web
        image: ghcr.io/rpersee/stremio/client:5.0.0-beta.4
        ports:
        - containerPort: 8080
