---
apiVersion: v1
kind: Service
metadata:
  name: stremio-service
spec:
  selector:
    app: stremio
    role: server
  ports:
  - name: backend
    protocol: TCP
    port: 11470
    targetPort: 11470
---
apiVersion: v1
kind: Service
metadata:
  name: stremio-web
spec:
  selector:
    app: stremio
    role: client
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 8080
