# Default values for stremio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/rpersee/stremio/client
  pullPolicy: IfNotPresent
  tag: "5.0.0-beta.4"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

server:
  enabled: true

  replicaCount: 1

  image:
    repository: ghcr.io/rpersee/stremio/server
    pullPolicy: IfNotPresent
    tag: "4.20.3"

  podAnnotations: {}
  podLabels: {}

  service:
    type: ClusterIP
    port: 11470
    annotations: {}

  resources: {}

  openvpn:
    image:
      repository: ghcr.io/qdm12/gluetun
      pullPolicy: IfNotPresent
      tag: "latest"

    resources: {}

    timezone: Europe/Paris

    credentials:
      secretName: openvpn-credentials
      usernameKey: username
      passwordKey: password

    configuration:
      secretName: openvpn-configuration
      filenameKey: custom.ovpn
