apiVersion: v1
kind: Service
metadata:
  name: {{ include "stremio.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "stremio.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stremio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client
