name: Build and publish images

on:
  workflow_call:
    inputs:
      build-matrix:
          required: true
          type: string
      platforms:
          required: false
          type: string
          default: "linux/amd64,linux/arm64"

jobs:
  docker:
    strategy:
      matrix: ${{ fromJson(inputs.build-matrix) }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}},value=${{ matrix.version }}

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ matrix.dockerfile || 'Dockerfile' }}
          context: ${{ matrix.context || '.' }}
          build-args: ${{ matrix.build-args }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
